version: "3"
volumes:
  pgdata:
networks:
  webnet:
services:
  db:
    image: postgres:latest
    deploy:
      restart_policy: 
        condition: any
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    networks:
      - webnet
    volumes:
      - pgdata:/var/lib/postgresql/data

